"""HTML email templates for parsing summary notifications."""


def df_to_html_table(df):
    """Convert DataFrame to styled HTML table."""
    if df.empty:
        return '<p>No records.</p>'

    html = '<table border="1" cellpadding="5" cellspacing="0" '
    html += 'style="border-collapse:collapse; font-family:Arial; font-size:12px;">\n'

    # Header
    html += '<tr style="background-color:#4472C4; color:white;">\n'
    for col in df.columns:
        html += '  <th style="padding:8px;">{}</th>\n'.format(col)
    html += '</tr>\n'

    # Rows
    for idx, row in df.iterrows():
        bg = '#D6E4F0' if idx % 2 == 0 else '#FFFFFF'
        html += '<tr style="background-color:{};">\n'.format(bg)
        for val in row:
            html += '  <td style="padding:6px;">{}</td>\n'.format(val)
        html += '</tr>\n'

    html += '</table>\n'
    return html


def build_summary_email(parsed_df, not_parsed_df):
    """Build the full HTML email body."""
    html = """
    <html>
    <body style="font-family: Arial, sans-serif; margin: 20px;">
        <h2 style="color: #2E4057;">MAYA Parsing Summary</h2>

        <h3 style="color: #4472C4;">Parsed Companies ({parsed_count})</h3>
        {parsed_table}

        <hr style="border: 1px solid #ccc;">

        <h3 style="color: #C44444;">Not Parsed / Pending ({not_parsed_count})</h3>
        {not_parsed_table}

        <br>
        <p style="font-size: 11px; color: #888;">
            Generated by MAYA Enhanced Pipeline
        </p>
    </body>
    </html>
    """.format(
        parsed_count=len(parsed_df),
        parsed_table=df_to_html_table(parsed_df),
        not_parsed_count=len(not_parsed_df),
        not_parsed_table=df_to_html_table(not_parsed_df),
    )
    return html
